import  "bootstrap/dist/css/bootstrap.min.css"
import "./globals.css"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  console.log('enter in frontend')
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  )
}
