import  "bootstrap/dist/css/bootstrap.min.css"
import "./globals.css"
import Script from "next/script"
import Header from "./organisms/Header/Header"
import Footer from "./organisms/Footer/Footer"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  console.log('enter in frontend')
  return (
    <html lang="en">

      <body>
        <Header />
        {children}
        <Footer />
        <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" />
      </body>
    </html>
  )
}
